---
# Add the Java ppa repository
- name: Add Java repository
  apt_repository:
   repo: ppa:webupd8team/java

# Automatically accepts the Oracle License popup in the terminal
- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install dependencies
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:  
    - apt-transport-https
    - python-pip
    - ca-certificates
    - sudo
    - wget
    - curl
    - python-passlib
    - oracle-java8-installer
    - logstash
    - kibana
    - nginx
    - elasticsearch